# Generated by Django 3.0.7 on 2020-06-20 19:02

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200620_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Take_Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=blog.models.unique_file_path)),
            ],
        ),
    ]
