# Generated by Django 3.0.7 on 2020-06-21 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post2',
            name='post_image',
            field=models.ImageField(default='default.jpg', upload_to='post2_pics'),
        ),
    ]
